pub const XCF_TILE_WIDTH = 64;
pub const XCF_TILE_HEIGHT = 64;
pub const XCF_TILE_MAX_DATA_LENGTH_FACTOR = 1.5;
pub const XCF_TILE_SAVE_BATCH_SIZE = 128;

pub const PropType = enum(u32) {
    PROP_END = 0,
    PROP_COLORMAP = 1,
    PROP_ACTIVE_LAYER = 2,
    PROP_ACTIVE_CHANNEL = 3,
    PROP_SELECTION = 4,
    PROP_FLOATING_SELECTION = 5,
    PROP_OPACITY = 6,
    PROP_MODE = 7,
    PROP_VISIBLE = 8,
    PROP_LINKED = 9,
    PROP_LOCK_ALPHA = 10,
    PROP_APPLY_MASK = 11,
    PROP_EDIT_MASK = 12,
    PROP_SHOW_MASK = 13,
    PROP_SHOW_MASKED = 14,
    PROP_OFFSETS = 15,
    PROP_COLOR = 16,
    PROP_COMPRESSION = 17,
    PROP_GUIDES = 18,
    PROP_RESOLUTION = 19,
    PROP_TATTOO = 20,
    PROP_PARASITES = 21,
    PROP_UNIT = 22,
    PROP_PATHS = 23,
    PROP_USER_UNIT = 24,
    PROP_VECTORS = 25,
    PROP_TEXT_LAYER_FLAGS = 26,
    PROP_OLD_SAMPLE_POINTS = 27,
    PROP_LOCK_CONTENT = 28,
    PROP_GROUP_ITEM = 29,
    PROP_ITEM_PATH = 30,
    PROP_GROUP_ITEM_FLAGS = 31,
    PROP_LOCK_POSITION = 32,
    PROP_FLOAT_OPACITY = 33,
    PROP_COLOR_TAG = 34,
    PROP_COMPOSITE_MODE = 35,
    PROP_COMPOSITE_SPACE = 36,
    PROP_BLEND_SPACE = 37,
    PROP_FLOAT_COLOR = 38,
    PROP_SAMPLE_POINTS = 39,
    PROP_ITEM_SET = 40,
    PROP_ITEM_SET_ITEM = 41,
    PROP_LOCK_VISIBILITY = 42,
    PROP_SELECTED_PATH = 43,
    PROP_FILTER_REGION = 44,
    PROP_FILTER_ARGUMENT = 45,
    PROP_FILTER_CLIP = 46,
    PROP_VECTOR_LAYER = 47,
    PROP_LINK_LAYER = 48,
    PROP_TRANSFORM = 49,
    _,
};

pub const XcfCompressionType = enum(u8) {
    COMPRESS_NONE = 0,
    COMPRESS_RLE = 1,
    COMPRESS_ZLIB = 2,
    COMPRESS_FRACTAL = 3,
    _,
};

pub const XcfOrientationType = enum(u32) {
    XCF_ORIENTATION_HORIZONTAL = 1,
    XCF_ORIENTATION_VERTICAL = 2,
    _,
};

pub const XcfStrokeType = enum(u32) {
    XCF_STROKETYPE_STROKE = 0,
    XCF_STROKETYPE_BEZIER_STROKE = 1,
    _,
};

pub const XcfGroupItemFlagsType = enum(u32) {
    XCF_GROUP_ITEM_EXPANDED = 1,
    _,
};

pub const GimpImageBaseType = enum(i32) {
    GIMP_RGB = 0,
    GIMP_GRAY = 1,
    GIMP_INDEXED = 2,
    _,
};

pub const GimpImageType = enum(i32) {
    GIMP_RGB_IMAGE = 0,
    GIMP_RGBA_IMAGE = 1,
    GIMP_GRAY_IMAGE = 2,
    GIMP_GRAYA_IMAGE = 3,
    GIMP_INDEXED_IMAGE = 4,
    GIMP_INDEXEDA_IMAGE = 5,
    _,
};
